#!/usr/bin/env bash
# change host file
mv /etc/hosts /etc/hosts.bak
grep -v 'localhost' /etc/hosts.bak > /etc/hosts
echo '127.0.0.2       localhost' >> /etc/hosts
echo '8.8.8.8       facebook.com' >> /etc/hosts
